name: Checkov
on:
  push:
    branches:
      - tflint-3
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          output_format: cli,sarif
          output_file_path: console,results.sarif
          directory: ./prod/
          framework: terraform 
          soft_fail: false   # when true then any error step will goes to next & false then step stopped on error
