name: tfsec          
permissions: write-all
on:
  pull_request:
  workflow_dispatch:
jobs:
  tfsec:
    uses: clouddrove/github-shared-workflows/.github/workflows/tfsec.yml@1.0.5
    # secrets: inherit
    secrets:
      GITHUB: ${{ secrets.GITHUB }}
    with:
      working_directory: './'
